spring:
  jpa:
    show-sql: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: vimerobox@gmail.com
    password: rony123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-timeout: 30000
      auto-commit: false
      pool-name: engine_pool_ms
      minimum-idle: 5
    username: ${INFRA_DB_ORACLE_USERNAME}
    password: ${INFRA_DB_ORACLE_PASSWORD}
    url: ${INFRA_DB_ORACLE_URL}

  flyway:
    enabled: false
    baselineOnMigrate: true
    table: schema_version_sovio

  jackson:
    default-property-inclusion: non_null

app:
  cors:
    url:
      - http://127.0.0.1:4200
      - http://localhost:4200
      - https://sovio.vimero.dev
    max-age: 3600
    methods:
      - GET
      - POST
      - PUT

keycloak:
  enabled: false

pide:
  enabled: false

sendgrid:
  apiKey: ${INFRA_MAIL_SENDGRID_API_KEY}
  from: rony@vimero.io


logging:
  level:
    root: info

security:
  secret: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
  algorithm: HS512
  login: /auth/login
  expiration: 3000000
  allow-urls:
    - /onboard/**